swagger: "2.0"
info:
  title: Academy API
  description: >
                Methods for managing Hashicorp Academy
  version: 1.0.0
basePath: /api
produces:
  - application/json
x-google-backend:
        address: https://api-service-uhx7ntyxaa-uc.a.run.app
paths:
  /member:
    get:
      tags:
        - Members
      summary: get member properties
      operationId: getMember
      parameters:
        - in: query
          name: id
          type: string
          description: member id
          required: true
      security:
          - api_key: []
      responses:
        200:
          description: OK
    post:
      tags:
        - Members
      summary: create a member
      operationId: postMember
      parameters:
        - name: member
          in: body
          schema: {
            "$ref": "#/definitions/Member"
          }
          description: Json object with member properties
          required: true
      security:
          - api_key: []
      responses:
        200:
          description: OK
  /course:
    get:
      tags:
        - Courses
      summary: get a course
      operationId: getCourse
      parameters:
        - in: query
          name: id
          type: string
          description: course id
          required: true
      security:
          - api_key: []
      responses:
        200:
          description: OK
    post:
      tags:
        - Courses
      summary: create a course
      operationId: postCourse
      parameters:
        - name: course
          in: body
          schema: {
            "$ref": "#/definitions/Course"
          }
          description: Json object with course properties
          required: true
      security:
          - api_key: []
      responses:
        200:
          description: OK
    delete:
      tags:
        - Courses
      summary: delete a course
      operationId: deleteCourse
      parameters:
        - in: query
          name: course_id
          type: string
          description: course id
          required: true
      security:
          - api_key: []
      responses:
        200:
          description: OK
  /invite:
    post:
      tags:
        - Invites
      summary: create an invite
      operationId: CreateInvite
      parameters:
        - name: data
          in: body
          schema:
            $ref: '#/definitions/Invite'
      security:
        - api_key: []
      responses:
        200:
          description: OK
  /report/members:
    get:
      tags:
        - Reports
      summary: Returns a list of all members
      operationId: getMemberReport
      security:
          - api_key: []
      responses:
        200:
          description: OK
  /report/courses:
    get:
      tags:
        - Reports
      summary: Returns a list of all coursees
      operationId: getCourseReport
      #security:
      #    - api_key: []
      responses:
        200:
          description: OK
  /report/invites:
    get:
      tags:
        - Reports
      summary: Returns a list of all invites
      operationId: getInviteReport
      security:
          - api_key: []
      responses:
        200:
          description: OK
  /report/creators:
    get:
      tags:
        - Reports
      summary: Returns a list of all code creators
      operationId: getCreatorReport
      security:
          - api_key: []
      responses:
        200:
          description: OK
  /code_creator:
    post:
      tags:
        - Access Code Creators
      summary: makes a new access code creation account
      operationId: postCreator
      parameters:
        - name: creator_id
          in: body
          schema: {
            "$ref": "#/definitions/Access Code Creator"
          }
          description: creator ID
          required: true
      security:
        - api_key: []
      responses:
        200:
          description: ok
  /code:
    get:
      tags:
        - Access Codes
      summary: validate an access code
      operationId: getValidation
      parameters:
        - in: query
          name: access_code
          type: string
          description: access code value
          required: true
      security:
        - api_key: []
      responses:
        200:
          description: ok
    post:
      tags:
        - Access Codes
      summary: generate an access code
      operationId: getLearner
      parameters:
        - name: creator code
          in: body
          schema: {
            "$ref": "#/definitions/Code Request"
          }
          description: creator code
          required: true
      security:
        - api_key: []
      responses:
        200:
          description: ok
  /redeem:
    post:
      tags:
        - Access Code Redemption
      summary: validate an access code
      operationId: postRedeem
      parameters:
        - in: query
          name: access_code
          type: string
          description: access code value
          required: true
        - in: query
          name: member_id
          type: string
          description: member id value
          required: true
      security:
        - api_key: []
      responses:
        200:
          description: ok
definitions:
  Member:
    type: object
    properties:
      data:
        type: object
        properties:
          id:
            type: string
            example: 102216623437578181514
          email:
            type: string
            example: member@company.org
          name:
            type: string
            example: Academy Member
          role:
            type: string
            example: learner
    required:
      - data
  Member Role:
    type: object
    properties:
      data:
        type: object
        properties:
          email:
              type: string
              example: learner@company.org
          role:
            type: string
            example: learner
          access_code:
              type: string
              example: XXXXRrYFca03e654

    required:
        - data
  Course:
    type: object
    properties:
      data:
        type: object
        properties:
          course_id:
            type: string
            example: 01.01.2021 Academy
          agenda:
            type: string
            example: Vault for Enterprise Customers
          session_start_date:
            type: string
            example: 01.01.2021
          session_start_time:
            type: string
            example: 9 AM EST
          capacity:
            type: integer
            minimum: 1
            maximum: 20
            example: 20
          instructor:
            type: string
            example: instructor@hashicorp.com
          learners:
            type: array
            example: ['learner1@company.org','learner2@company.org','learner3@company.org']
          instruqt_invite:
            type: string
            example: https://play.instruqt.com/HashiCorp-EA/invite/qanuciwpigd1
          zoom_link:
            type: string
            example: https://hashicorp.zoom.us/j/99966445299?pwd=MmNnVExDaEdTMlZSK2pBV3N3enVJQT09
    required:
      - data
  Invite:
    type: object
    properties:
      data:
          type: object
          properties:
            allowAnonymous:
              type: boolean
              example: False
            allowedEmailAddresses:
              type: array
              example: ["learner1@company.org"]
            inviteLimit:
              type: integer
              example: 0
            inviteTTL:
              type: integer
              example: 0
            playLimit:
              type: integer
              example: 0
            playTTL:
              type: integer
              example: 0
            title:
              type: string
              example: 01.01.2021 Vault Academy
            trackIDs:
              type: array
              example: ["ep8gn1ktns7r","ystg2lhd0df2"]

    required:
      - data
      - title
      - trackIDs
  Access Code Creator:
    type: object
    properties:
      data:
        type: object
        properties:
          email:
              type: string
              example: creator@company.org

    required:
        - data
  Code Request:
    type: object
    properties:
      data:
        type: object
        properties:
          creator_code:
              type: string
              example: XXXX
          member_type:
              type: string
              example: learner

    required:
        - data
securityDefinitions:
      api_key:
        type: "apiKey"
        name: "key"
        in: "query"
